stages:
  - test
  - build

test:
  image: python:3
  services:
    - name: postgres:latest
    - name: minio/minio:latest
      alias: minio
      entrypoint:
        - sh
        - -c
      command:
        - "mkdir -p /data/codes && minio server /data"
  variables:
    POSTGRES_DB: nabard_test
    POSTGRES_USER: nabard
    POSTGRES_PASSWORD: test_pass
    MINIO_ACCESS_KEY: NABARDTESET1234
    MINIO_SECRET_KEY: NABARDTESET1234
    APP_S3_ENDPOINT: http://minio:9000
    APP_S3_ACCESS_KEY: "$MINIO_ACCESS_KEY"
    APP_S3_SECRET_KEY: "$MINIO_SECRET_KEY"
    APP_DB_HOST: postgres
    APP_DB_USER: "$POSTGRES_USER"
    APP_DB_PASS: "$POSTGRES_PASSWORD"
    APP_DB_NAME: "$POSTGRES_DB"
  before_script:
    - python -V # Print out python version for debugging
    - pip install pipenv
    - pipenv install --dev
    - pipenv run ./manage.py migrate --noinput
  script:
    - pipenv run pytest
    - APP_DEBUG=false pipenv run ./manage.py collectstatic --no-input
  artifacts:
    when: on_success
    paths:
      - $CI_PROJECT_DIR/static
    expire_in: 3d
