language: python

python:
  - "3.8"

services: postgresql

env:
  global:
    - APP_DB_USER="postgres"
    - APP_DB_PASS=""
    - APP_DB_NAME="nabard"

install:
  - pip install pipenv
  - pipenv install --dev

before_script:
  - python -V
  - psql -c "CREATE DATABASE $APP_DB_NAME;" -U postgres
  - pipenv run ./manage.py migrate --noinput

script:
  - pipenv run pytest
