name: Continous Integration

on: [push, pull_request]

jobs:
  test:
    name: Test Execution
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: nabard_test
          POSTGRES_USER: nabard
          POSTGRES_PASSWORD: test_pass
        # Health checks to wait until postgres is ready
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      minio:
        image: nabardio/minio
        env:
          MINIO_ACCESS_KEY: NABARDACCESSKEY
          MINIO_SECRET_KEY: NabardSecretAcessKey
          MINIO_BUCKETS: codes
    env:
      APP_DB_HOST: postgres
      APP_DB_USER: nabard
      APP_DB_PASS: test_pass
      APP_DB_NAME: nabard_test
      APP_S3_ENDPOINT: http://minio:9000
      APP_S3_ACCESS_KEY: NABARDACCESSKEY
      APP_S3_SECRET_KEY: NabardSecretAcessKey

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8.x
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install pipenv
        run: pip install pipenv

      - name: Install dependencies
        run: pipenv install --dev

      - name: Setup the database
        run: pipenv run ./manage.py migrate --noinput

      - name: Run tests
        run: pipenv run pytest
